# Generated by Django 4.0.4 on 2022-04-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0004_match_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('message_type', models.CharField(max_length=240, null=True)),
                ('message', models.CharField(max_length=240, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contact_messagesdesignation', to='Turf_app.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contact_messagesuser', to='Turf_app.user_registration')),
            ],
        ),
    ]
