# Generated by Django 4.0.4 on 2022-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0005_contact_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='fullname',
            new_name='Firstname',
        ),
    ]
