# Generated by Django 4.0.4 on 2022-04-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0006_rename_fullname_user_registration_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matchesdesignation', to='Turf_app.designation'),
        ),
        migrations.AddField(
            model_name='matches',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matchesuser', to='Turf_app.user_registration'),
        ),
    ]
