# Generated by Django 4.0.4 on 2022-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0007_matches_designation_matches_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matdesignation', to='Turf_app.designation'),
        ),
    ]
