# Generated by Django 4.0.4 on 2022-04-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0008_alter_matches_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='designation',
        ),
    ]
