# Generated by Django 4.0.4 on 2022-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0009_remove_matches_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
