# Generated by Django 4.0.4 on 2022-04-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0013_rename_match_result_matchresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='location',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='location',
        ),
    ]
