# Generated by Django 4.0.4 on 2022-04-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0014_remove_matches_location_remove_matchresult_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='locationurl',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
