# Generated by Django 4.0.4 on 2022-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0015_turf_locationurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_messages',
            name='reply',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
