# Generated by Django 4.0.4 on 2022-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0016_contact_messages_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_messages',
            name='repliedto',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
