# Generated by Django 4.0.4 on 2022-04-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0017_contact_messages_repliedto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_messages',
            old_name='repliedto',
            new_name='repliedby',
        ),
    ]
