# Generated by Django 4.0.4 on 2022-04-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0018_rename_repliedto_contact_messages_repliedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_messages',
            name='replyto',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
