# Generated by Django 4.0.4 on 2022-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0019_contact_messages_replyto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='status',
            field=models.CharField(default='0', max_length=240, null=True),
        ),
    ]
