# Generated by Django 4.0.4 on 2022-04-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0020_alter_turf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='fromtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='matchname',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='fromtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='matchname',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_resultuser', to='Turf_app.user_registration'),
        ),
    ]
