# Generated by Django 4.0.4 on 2022-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0021_matches_fromtime_matches_matchname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='Playrate',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
