# Generated by Django 4.0.4 on 2022-04-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0022_turf_playrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('fromtime', models.TimeField(blank=True, null=True)),
                ('sport', models.CharField(max_length=240, null=True)),
                ('gamestructure', models.CharField(max_length=240, null=True)),
                ('Turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TurfBookingTurf', to='Turf_app.turf')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TurfBookingdesignation', to='Turf_app.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TurfBookinguser', to='Turf_app.user_registration')),
            ],
        ),
    ]
