# Generated by Django 4.0.4 on 2022-04-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0024_turfbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('bankname', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsccode', models.CharField(max_length=240, null=True)),
                ('branchname', models.CharField(max_length=240, null=True)),
                ('amount', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240, null=True)),
                ('Turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PaymentTurf', to='Turf_app.turf')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Paymentdesignation', to='Turf_app.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Paymentuser', to='Turf_app.user_registration')),
            ],
        ),
    ]
