# Generated by Django 4.0.4 on 2022-04-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0025_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='Ticketprice',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='quantity',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='total',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
