# Generated by Django 4.0.4 on 2022-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0026_matches_ticketprice_matches_quantity_matches_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='paymentstatus',
            field=models.CharField(default='0', max_length=240, null=True),
        ),
    ]
