# Generated by Django 4.0.4 on 2022-04-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0027_matches_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='matches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Paymentmatches', to='Turf_app.matches'),
        ),
    ]
