# Generated by Django 4.0.4 on 2022-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0028_payment_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='accountnumber',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='amount',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='bankname',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='branchname',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='ifsccode',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='paymentdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
