# Generated by Django 4.0.2 on 2022-05-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0029_matches_accountnumber_matches_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='firstteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_resultfirstteam', to='Turf_app.teams'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='loss_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_resultloss_team', to='Turf_app.teams'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='secondteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_resultsecondteam', to='Turf_app.teams'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='win_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_resultwin_team', to='Turf_app.teams'),
        ),
    ]
