# Generated by Django 4.0.4 on 2022-05-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0030_alter_matchresult_firstteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Shopcategoryuser', to='Turf_app.user_registration')),
            ],
        ),
    ]
