# Generated by Django 4.0.4 on 2022-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0034_shopitems_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='description',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
