# Generated by Django 4.0.4 on 2022-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0035_shopitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='size',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
