# Generated by Django 4.0.2 on 2022-05-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0036_shopitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='color',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
