# Generated by Django 4.0.4 on 2022-05-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0038_shopitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='finalprice',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
