# Generated by Django 4.0.4 on 2022-05-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0039_shopitems_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='subtotal',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shopitems',
            name='tax',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shopitems',
            name='total',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
