# Generated by Django 4.0.4 on 2022-05-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0040_shopitems_subtotal_shopitems_tax_shopitems_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.CharField(max_length=240, null=True)),
                ('tax', models.CharField(max_length=240, null=True)),
                ('total', models.CharField(max_length=240, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('bankname', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsccode', models.CharField(max_length=240, null=True)),
                ('branchname', models.CharField(max_length=240, null=True)),
                ('amount', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240, null=True)),
                ('Shopitems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Shoppaymentuser', to='Turf_app.shopitems')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Shoppaymentuser', to='Turf_app.user_registration')),
            ],
        ),
    ]
