# Generated by Django 4.0.4 on 2022-05-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0042_shopcategory_designation_shopitems_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShopitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=240, null=True)),
                ('itemname', models.CharField(max_length=240, null=True)),
                ('price', models.CharField(max_length=240, null=True)),
                ('size', models.CharField(max_length=240, null=True)),
                ('color', models.CharField(max_length=240, null=True)),
                ('quantity', models.CharField(max_length=240, null=True)),
                ('finalprice', models.CharField(max_length=240, null=True)),
                ('subtotal', models.CharField(max_length=240, null=True)),
                ('tax', models.CharField(max_length=240, null=True)),
                ('total', models.CharField(max_length=240, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AddShopitemsuser', to='Turf_app.shopcategory')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AddShopitemsdesignation', to='Turf_app.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AddShopitemssuser', to='Turf_app.user_registration')),
            ],
        ),
    ]
