# Generated by Django 4.0.4 on 2022-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0043_addshopitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addshopitems',
            name='finalprice',
        ),
        migrations.RemoveField(
            model_name='addshopitems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='addshopitems',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='addshopitems',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='addshopitems',
            name='total',
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='category',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
