# Generated by Django 4.0.4 on 2022-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0044_remove_addshopitems_finalprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppayment',
            name='items',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
