# Generated by Django 4.0.4 on 2022-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0045_shoppayment_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='deliverydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
