# Generated by Django 4.0.4 on 2022-05-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0046_shopitems_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='turfuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matchesturfuser_id', to='Turf_app.user_registration'),
        ),
    ]
