# Generated by Django 4.0.4 on 2022-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf_app', '0047_matches_turfuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='turfuser_id',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
